Catkin-ProjectName: win_ros
Version: 0.2.0
Description: This stack provides resources and code for windows-ros development.
Author: Daniel Stonier <d.stonier@gmail.com>
Maintainer: Daniel Stonier <d.stonier@gmail.com>
Homepage: http://ros.org/wiki/win_ros

Depends: catkin, std_msgs, ros_comm

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
#Catkin-ROS-Message-Generator: cpp
